# port
port: 8080

# root folder
root: public

# index file
index: index.html

# history API
# if enabled, deposito will serve index for unfound documents
history API: true

# not found
# if specified, deposito will serve this file for unfound documents
not found: 404.html

# custom mime
# allow to (re)define any mime type
# deposito includes https://github.com/broofa/node-mime/tree/master/types
mime:
  # text/example: [extension1, extension2]

# Content-Security-Policy https://developer.mozilla.org/en-US/docs/Web/Security/CSP/CSP_policy_directives
CSP:
  default-src: self
  style-src:
    - self
    - unsafe-inline
  script-src:
    - self
    - unsafe-eval
  img-src: '*'
  media-src: '*'
  font-src: '*'
  connect-src: '*'
  object-src: none
  child-src: none
  frame-ancestors: none
  report-uri: none


# X-Frame-Option
frame: 'DENY'